name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: swift build
        run: swift build --product kwwk
      - name: swift test
        run: swift test

  build-linux:
    runs-on: ubuntu-latest
    container: swift:6.1
    steps:
      - uses: actions/checkout@v4
      - name: swift build
        run: swift build --product kwwk
      - name: swift test
        run: swift test
